name: lint_strict_dependencies
description: Linter for strict dependencies
version: 0.0.2
homepage: https://github.com/decoch/lint_strict_dependencies

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.7
